-- Scooter Rent Kandy: initial schema.
-- Enums are stored as VARCHAR so new values don't require a migration of a DB enum type.

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL UNIQUE,
    password_hash       VARCHAR(255) NOT NULL,
    full_name           VARCHAR(255) NOT NULL,
    phone               VARCHAR(50),
    role                VARCHAR(20)  NOT NULL,
    id_document_number  VARCHAR(100),
    driving_license_no  VARCHAR(100),
    country             VARCHAR(100),
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP    NOT NULL
);

CREATE TABLE scooters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)    NOT NULL UNIQUE,
    model           VARCHAR(120)   NOT NULL,
    plate_number    VARCHAR(50)    NOT NULL UNIQUE,
    engine_cc       INTEGER,
    status          VARCHAR(20)    NOT NULL,
    daily_rate      NUMERIC(12, 2) NOT NULL,
    deposit_amount  NUMERIC(12, 2) NOT NULL,
    odometer_km     INTEGER        NOT NULL DEFAULT 0,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    image_url       VARCHAR(500),
    description     VARCHAR(2000),
    created_at      TIMESTAMP      NOT NULL
);

CREATE TABLE gear_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120)   NOT NULL,
    category        VARCHAR(50)    NOT NULL,
    description     VARCHAR(1000),
    daily_rate      NUMERIC(12, 2) NOT NULL,
    total_quantity  INTEGER        NOT NULL,
    active          BOOLEAN        NOT NULL DEFAULT TRUE
);

CREATE TABLE bookings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference        VARCHAR(30)    NOT NULL UNIQUE,
    customer_id      BIGINT         NOT NULL REFERENCES users (id),
    scooter_id       BIGINT         NOT NULL REFERENCES scooters (id),
    start_date       DATE           NOT NULL,
    end_date         DATE           NOT NULL,
    rental_days      INTEGER        NOT NULL,
    status           VARCHAR(30)    NOT NULL,
    scooter_cost     NUMERIC(12, 2) NOT NULL,
    gear_cost        NUMERIC(12, 2) NOT NULL,
    deposit_amount   NUMERIC(12, 2) NOT NULL,
    total_amount     NUMERIC(12, 2) NOT NULL,
    pickup_location  VARCHAR(255),
    notes            VARCHAR(2000),
    start_odometer   INTEGER,
    end_odometer     INTEGER,
    damage_charge    NUMERIC(12, 2),
    checked_out_at   TIMESTAMP,
    returned_at      TIMESTAMP,
    cancelled_at     TIMESTAMP,
    created_at       TIMESTAMP      NOT NULL
);
CREATE INDEX idx_bookings_scooter_dates ON bookings (scooter_id, start_date, end_date);
CREATE INDEX idx_bookings_customer ON bookings (customer_id);

CREATE TABLE booking_gear (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    gear_item_id  BIGINT         NOT NULL REFERENCES gear_items (id),
    quantity      INTEGER        NOT NULL,
    daily_rate    NUMERIC(12, 2) NOT NULL,
    line_total    NUMERIC(12, 2) NOT NULL
);

CREATE TABLE contracts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT        NOT NULL UNIQUE REFERENCES bookings (id) ON DELETE CASCADE,
    contract_number  VARCHAR(40)   NOT NULL UNIQUE,
    terms_version    VARCHAR(20)   NOT NULL,
    terms_text       VARCHAR(20000) NOT NULL,
    signed_name      VARCHAR(255),
    signed_ip        VARCHAR(64),
    signed_at        TIMESTAMP,
    created_at       TIMESTAMP     NOT NULL
);

CREATE TABLE payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    BIGINT         NOT NULL REFERENCES bookings (id),
    amount        NUMERIC(12, 2) NOT NULL,
    type          VARCHAR(20)    NOT NULL,
    method        VARCHAR(20)    NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    provider      VARCHAR(30)    NOT NULL,
    provider_ref  VARCHAR(100),
    card_last4    VARCHAR(4),
    failure_reason VARCHAR(255),
    created_at    TIMESTAMP      NOT NULL
);
CREATE INDEX idx_payments_booking ON payments (booking_id);

CREATE TABLE invoices (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number  VARCHAR(40)    NOT NULL UNIQUE,
    booking_id      BIGINT         NOT NULL REFERENCES bookings (id),
    kind            VARCHAR(20)    NOT NULL,
    status          VARCHAR(20)    NOT NULL,
    currency        VARCHAR(3)     NOT NULL,
    subtotal        NUMERIC(12, 2) NOT NULL,
    tax             NUMERIC(12, 2) NOT NULL,
    total           NUMERIC(12, 2) NOT NULL,
    issued_at       TIMESTAMP      NOT NULL
);

CREATE TABLE invoice_lines (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id   BIGINT         NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    description  VARCHAR(255)   NOT NULL,
    quantity     INTEGER        NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    amount       NUMERIC(12, 2) NOT NULL
);

CREATE TABLE maintenance_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scooter_id      BIGINT         NOT NULL REFERENCES scooters (id),
    type            VARCHAR(20)    NOT NULL,
    status          VARCHAR(20)    NOT NULL,
    description     VARCHAR(2000)  NOT NULL,
    cost            NUMERIC(12, 2),
    scheduled_date  DATE,
    completed_date  DATE,
    odometer_km     INTEGER,
    created_at      TIMESTAMP      NOT NULL
);

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL REFERENCES users (id),
    channel     VARCHAR(20)   NOT NULL,
    subject     VARCHAR(255)  NOT NULL,
    message     VARCHAR(4000) NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    read_at     TIMESTAMP,
    created_at  TIMESTAMP     NOT NULL
);
CREATE INDEX idx_notifications_user ON notifications (user_id);

CREATE TABLE gps_pings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scooter_id   BIGINT           NOT NULL REFERENCES scooters (id),
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    speed_kmh    DOUBLE PRECISION,
    recorded_at  TIMESTAMP        NOT NULL
);
CREATE INDEX idx_gps_pings_scooter_time ON gps_pings (scooter_id, recorded_at);
