-- Audit trail of every payment-provider call (SDS 6.2 audit logging, 8.3 payment retention). The single Payment
-- row per booking stays the record of what the booking was charged; each transaction underneath it keeps the
-- provider reference of one call: the initial intent, a remaining-balance charge or intent, or a refund.

CREATE TABLE payment_transactions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      BIGINT         NOT NULL REFERENCES payments (id),
    kind            VARCHAR(20)    NOT NULL,
    provider_ref    VARCHAR(255),
    amount          NUMERIC(10, 2) NOT NULL,
    status          VARCHAR(20)    NOT NULL,
    failure_reason  VARCHAR(255),
    created_at      TIMESTAMP      NOT NULL,
    CONSTRAINT ck_payment_tx_kind CHECK (kind IN ('INITIAL', 'BALANCE', 'REFUND')),
    CONSTRAINT ck_payment_tx_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_payment_tx_amount CHECK (amount > 0)
);
CREATE INDEX idx_payment_tx_payment ON payment_transactions (payment_id, created_at);

-- One INITIAL transaction per existing payment, from its stored intent reference. Payments created before V3
-- were consolidated from several charges; their individual provider references are kept in legacy_payments.
INSERT INTO payment_transactions (payment_id, kind, provider_ref, amount, status, failure_reason, created_at)
SELECT id, 'INITIAL', stripe_payment_id, amount,
       CASE status WHEN 'PENDING' THEN 'PENDING' WHEN 'FAILED' THEN 'FAILED' ELSE 'SUCCESS' END,
       failure_reason, COALESCE(paid_at, created_at)
  FROM payments;

-- Refunded payments also get the REFUND transaction (its provider reference was not stored before V4).
INSERT INTO payment_transactions (payment_id, kind, provider_ref, amount, status, failure_reason, created_at)
SELECT id, 'REFUND', NULL, amount, 'SUCCESS', NULL, COALESCE(paid_at, created_at)
  FROM payments
 WHERE status = 'REFUNDED';
