-- SDS 2.2 GPS Log: bookingId NOT NULL (logs exist only during an active rental), latitude/longitude DECIMAL(9,6),
-- speed DECIMAL(5,2) NOT NULL >= 0. SDS 4.3 detectSpeedViolation(speed, 60 km/h), 5.2 admin speed-violation alerts.

-- Scooter last-known state, updated by every ping (including idle pings, which are no longer stored as GPS logs).
-- last_speed_kmh makes violation detection persistent: an alert fires when it goes from <= 60 to > 60.
ALTER TABLE scooters ADD COLUMN last_seen_at TIMESTAMP;
ALTER TABLE scooters ADD COLUMN last_speed_kmh NUMERIC(5, 2);
UPDATE scooters SET last_seen_at = (SELECT MAX(g.recorded_at) FROM gps_pings g WHERE g.scooter_id = scooters.id);
UPDATE scooters SET last_speed_kmh = (
    SELECT g.speed_kmh FROM gps_pings g WHERE g.scooter_id = scooters.id
     ORDER BY g.recorded_at DESC, g.id DESC FETCH FIRST 1 ROWS ONLY);

-- Pings recorded while no rental was under way are archived, then removed from the GPS log.
CREATE TABLE legacy_gps_pings_unlinked AS SELECT * FROM gps_pings WHERE booking_id IS NULL;
DELETE FROM gps_pings WHERE booking_id IS NULL;
ALTER TABLE gps_pings ALTER COLUMN booking_id SET NOT NULL;

-- Full-precision coordinates and speeds are archived before rounding to the SDS precision.
CREATE TABLE legacy_gps_ping_precision AS SELECT id, latitude, longitude, speed_kmh FROM gps_pings;
ALTER TABLE gps_pings ALTER COLUMN latitude SET DATA TYPE NUMERIC(9, 6);
ALTER TABLE gps_pings ALTER COLUMN longitude SET DATA TYPE NUMERIC(9, 6);
-- Fails (and the migration rolls back) if any logged ping has no speed: there is no value to invent.
ALTER TABLE gps_pings ALTER COLUMN speed_kmh SET DATA TYPE NUMERIC(5, 2);
ALTER TABLE gps_pings ALTER COLUMN speed_kmh SET NOT NULL;
ALTER TABLE gps_pings ADD CONSTRAINT ck_gps_pings_speed CHECK (speed_kmh >= 0);

-- One row per crossing above 60 km/h; feeds the admin dashboard panel and the alert messages.
CREATE TABLE speed_violations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scooter_id   BIGINT        NOT NULL REFERENCES scooters (id),
    booking_id   BIGINT        REFERENCES bookings (id),
    speed_kmh    NUMERIC(5, 2) NOT NULL,
    latitude     NUMERIC(9, 6) NOT NULL,
    longitude    NUMERIC(9, 6) NOT NULL,
    recorded_at  TIMESTAMP     NOT NULL,
    created_at   TIMESTAMP     NOT NULL
);
CREATE INDEX idx_speed_violations_recorded ON speed_violations (recorded_at);
